# Generated by Django 5.2.12 on 2026-04-13 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_team_alter_tournament_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Coach"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coached_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
