# Generated by Django 5.2.12 on 2026-04-13 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_team_coach"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("setter", "Setter"),
                            ("outside_hitter", "Outside Hitter"),
                            ("opposite", "Opposite Hitter"),
                            ("middle_blocker", "Middle Blocker"),
                            ("libero", "Libero"),
                            ("defensive_specialist", "Defensive Specialist"),
                        ],
                        max_length=50,
                    ),
                ),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Player"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tournaments.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "player")},
            },
        ),
    ]
