# Generated by Django 5.2.12 on 2026-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_teammembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="tournaments", to="tournaments.team"
            ),
        ),
    ]
