# Generated by Django 6.0.3 on 2026-04-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
