# Generated by Django 6.0.4 on 2026-04-26 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('set_1', 'Set 1'), ('set_2', 'Set 2'), ('set_3', 'Set 3'), ('set_4', 'Set 4'), ('set_5', 'Set 5'), ('full_match', 'Full Match')], default='full_match', max_length=20)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('blocks', models.PositiveIntegerField(default=0)),
                ('digs', models.PositiveIntegerField(default=0)),
                ('aces', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_stats', to='tournaments.match')),
                ('player', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Player'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_stats', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_stats', to='tournaments.team')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
