# Generated by Django 5.2.12 on 2026-04-14 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "tournaments",
            "0008_alter_match_id_alter_notification_id_alter_team_id_and_more",
        ),
        ("tournaments", "0008_match_away_score_match_home_score"),
    ]

    operations = []
