# Generated by Django 6.0.3 on 2026-04-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_team_losses_team_points_team_wins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-points', '-wins']},
        ),
    ]
