# Generated by Django 6.0.4 on 2026-04-26 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_performancestat'),
        ('tournaments', '0010_alter_team_options'),
    ]

    operations = [
    ]
