# Generated by Django 6.0.4 on 2026-04-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_task_attendance_playeravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='team',
        ),
    ]
