# Generated by Django 6.0.4 on 2026-04-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_remove_attendance_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_number', 'match_date', 'match_time']},
        ),
        migrations.AddField(
            model_name='match',
            name='bracket',
            field=models.CharField(blank=True, choices=[('winners', 'Winners'), ('losers', 'Losers'), ('grand_final', 'Grand Final')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='points_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points_for',
            field=models.IntegerField(default=0),
        ),
    ]
