# Generated by Django 5.2.12 on 2026-04-26 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0009_merge_20260414_1418"),
        (
            "tournaments",
            "0014_alter_match_options_match_bracket_match_round_number_and_more",
        ),
    ]

    operations = []
