# Generated by Django 5.2.12 on 2026-04-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0016_alter_attendance_id_alter_performancestat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="tournaments.announcement",
            ),
        ),
    ]
